# The workflow to publish package
name: Production

# Controls when the workflow will run
on:
  release:
    types: [ created ]
    branches: [ main ]

jobs:
  publish:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    steps:
      - name: "Checkout the repository"
        uses: actions/checkout@v4

      - name: "Use Node.js 20.x version"
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          cache-dependency-path: package-lock.json

      - name: "Install dependencies and build"
        run: npm ci && npm run build

      - name: "Set registry to NPM Packages"
        uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: 'https://registry.npmjs.org'

      - name: "Publish to NPM Packages"
        run: npm publish ./dist --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}

      - name: "Set registry to GitHub Packages"
        uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: 'https://npm.pkg.github.com'

      - name: "Publish to GitHub Packages"
        run: npm publish ./dist
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GH_ACCESS_TOKEN }}
