# The workflow to publish package
name: Production

# Controls when the workflow will run
on:
  release:
    types: [ created ]
    branches: [ main ]

jobs:
  publish:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    steps:
      - name: "Checkout repository"
        uses: actions/checkout@v3

      - name: "Install dependencies and build"
        run: npm install && npm run build

      # publish to NPM
      - uses: actions/setup-node@v3
        with:
          node-version: 'lts/*'
          registry-url: 'https://registry.npmjs.org'
      - run: npm publish ./dist --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}

      # publish to GitHub
      - uses: actions/setup-node@v3
        with:
          node-version: 'lts/*'
          registry-url: 'https://npm.pkg.github.com'
      - run: npm publish ./dist
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GH_ACCESS_TOKEN }}
